version: '3.7'

services:
  database:
    image: postgres:10.5
    environment:
      - POSTGRES_DB=practical_microservices
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
